openapi: 3.0.0
info: 
  description: |+
    Esta é a API de dados do Hypatiamat, na qual o Backoffice do Hypatimat realiza pedidos, de forma a apresentar os dados aos seus utilizadores. Todas as transações de dados passam por este serviço, que possuí diversas rotas com diferentes funções.
    
    Existem 5 tipos de utilizadores:
      - Aluno;
      - Professor;
      - Agrupamento;
      - Município;
      - Administrador.
    
    Cada tipo de utilizador tem autorização a executar determinadas rotas com determinados parâmetros especificados ao longo desta página.
    
    Além destes utilizadores, existem 2 utilizadores experimentais com o nível de autorização mais baixo para o aluno e professsor. 
  version: 1.4.0
  title: API de Dados do Hypatiamat
servers:
  - url: https://api.hypatiamat.com/
    description: Servidor da API. 
  - url : http://localhost:3050/
    description : Servidor em desenvolvimento.
tags:
  - name: Login
    description: Responsável pela autenticação no sistema.
  - name: Escolas
    description: Rotas disponibilizadas sobre os Agupamentos de escolas.
  - name: Professores
    description: Rotas disponibilizadas sobre os professores.
  - name: Alunos
    description: Rotas disponibilizadas sobre os alunos.
  - name: Turmas
    description: Rotas disponibilizadas sobre as turmas.
  - name: Jogos
    description: Rotas disponibilizadas sobre os jogos.
  - name: Aplicações de Conteúdo
    description: Rotas disponibilizadas sobre as aplicações de conteúdo.
  - name: Tarefas de Aplicações de Conteúdo
    description: Rotas disponibilizadas sobre tarefas de aplicações de conteúdo.
  - name: Quarentena
    description: Rotas disponibilizadas sobre os pedidos de inscrição.
  - name: Campeonatos
    description: Rotas disponibilizadas sobre os campeonatos.
  - name: Novidades
    description: Rotas disponibilizadas sobre as novidades.
  - name: Comunidades
    description: Rotas disponibilizadas sobre as comunidades.
  - name: Códigos de Professor
    description: Rotas disponibilizadas sobre os códigos de professor.
  - name: Troféus
    description: Rotas disponibilizadas sobre os troféus.
  - name: Mensagens
    description: Rotas disponibilizadas sobre as mensagens.
  - name: Cromos
    description: Rotas disponibilizadas sobre os cromos.
paths: !!inc/dir [ 'paths' ] 
components:
  schemas: !!inc/dir [ 'schemas', { excludeTopLevelDirSeparator: true, recursive: false }]
  securitySchemes:
    tokenQuery:
      type: apiKey
      in: query
      name: token
      description: 'Introduza o seu token.'
  responses:
    UnauthorizedToken:
      description: Para realizar este pedido, necessita de estar autenticado ou possuir um token. O seu token expirou?
    PermissionsUser:
      description: Não tem permissões suficientes para realizar o pedido.
    InvalidParameters:
      description: Algum campo obrigatório está em falta ou não é válido.
  examples: !!inc/dir [ 'examples', { excludeTopLevelDirSeparator: true, recursive: false }]